### ISSUE TITLE
Intermittent failures of test due to Dashboard not loading in time

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-e2e-tests#32]
Couple of time I've noticed the following failure in CI checks. See the snippets or full [console log](https://jenkins-syndesis-ci.b6ff.rh-idev.openshiftapps.com/job/syndesis-e2e-tests/job/master/28/console)

The crucial part is the start when we navigate to Dashboard or Home page and that particular page is not loaded in time/empty during following clicks. 

Make sure to handle such cases properly. 

```
 [32m✔ When "Camilla" navigates to the "Dashboard" page to see what's available in the Syndesis[
 [32m✔ And clicks on the "Create Integration" button to create a new integration.[39m
  [31m✖ Then she is presented with a visual integration editor[39m
```

```
14) Scenario: [1mCreate integration[22m - [90me2e/narratives/08-first-pass.feature:15[39m
    Step: [1mThen she is presented with a visual integration editor[22m - [90me2e/narratives/08-first-pass.feature:18[39m
    Step Definition: [90mnode_modules/cucumber-tsflow/src/BindingDecorator.ts:163[39m
    Message:
      [31mAssertionError: there must be edit page root element: expected false to be true
          at /home/jenkins/workspace/syndesis-e2e-tests_master-T3LXHLH4EPAVX4E4OGU73HSCISH2FS2SDVT6KMVDFTLN5LHCVFNA/node_modules/chai-as-promised/lib/chai-as-promised.js:305:22
          at ManagedPromise.invokeCallback_ (/home/jenkins/workspace/syndesis-e2e-tests_master-T3LXHLH4EPAVX4E4OGU73HSCISH2FS2SDVT6KMVDFTLN5LHCVFNA/node_modules/selenium-webdriver/lib/promise.js:1366:14)
          at TaskQueue.execute_ (/home/jenkins/workspace/syndesis-e2e-tests_master-T3LXHLH4EPAVX4E4OGU73HSCISH2FS2SDVT6KMVDFTLN5LHCVFNA/node_modules/selenium-webdriver/lib/promise.js:2970:14)
          at TaskQueue.executeNext_ (/home/jenkins/workspace/syndesis-e2e-tests_master-T3LXHLH4EPAVX4E4OGU73HSCISH2FS2SDVT6KMVDFTLN5LHCVFNA/node_modules/selenium-webdriver/lib/promise.js:2953:27)
          at asyncRun (/home/jenkins/workspace/syndesis-e2e-tests_master-T3LXHLH4EPAVX4E4OGU73HSCISH2FS2SDVT6KMVDFTLN5LHCVFNA/node_modules/selenium-webdriver/lib/promise.js:2813:27)
          at /home/jenkins/workspace/syndesis-e2e-tests_master-T3LXHLH4EPAVX4E4OGU73HSCISH2FS2SDVT6KMVDFTLN5LHCVFNA/node_modules/selenium-webdriver/lib/promise.js:676:7
          at <anonymous>
          at process._tickCallback (internal/process/next_tick.js:188:7)[39m
```

**Comment by dsimansk** [comment]
Doesn't seem to be an issue anymore. @jludvice @lvydra I'll close it, feel free to reopen anytime it reoccurs.
