### ISSUE TITLE
Investigate multiple step integration test failure

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-e2e-tests#43]
As discussed during today's meeting, there's a failure in multiple-step-integration. Pls take a look as a priority.

This also takes down protractor so definitely need a bit of care.

https://jenkins-syndesis-ci.b6ff.rh-idev.openshiftapps.com/job/syndesis-e2e-tests/job/master/32/console

```
[07:02:39] E/launcher - unknown error: Element <span _ngcontent-c7="" class="parent-step ">...</span> is not clickable at point (174, 76). Other element would receive the click: <a _ngcontent-c0="" href="/dashboard">...</a>
  (Session info: chrome=59.0.3071.115)
  (Driver info: chromedriver=2.30.477691 (6ee44a7247c639c0703f291d320bdf05c1531b57),platform=Linux 3.10.0-514.25.2.el7.x86_64 x86_64)
[07:02:39] E/launcher - WebDriverError: unknown error: Element <span _ngcontent-c7="" class="parent-step ">...</span> is not clickable at point (174, 76). Other element would receive the click: <a _ngcontent-c0="" href="/dashboard">...</a>
  (Session info: chrome=59.0.3071.115)
  (Driver info: chromedriver=2.30.477691 (6ee44a7247c639c0703f291d320bdf05c1531b57),platform=Linux 3.10.0-514.25.2.el7.x86_64 x86_64)
    at Object.checkLegacyResponse (/home/jenkins/workspace/syndesis-e2e-tests_master-T3LXHLH4EPAVX4E4OGU73HSCISH2FS2SDVT6KMVDFTLN5LHCVFNA/node_modules/selenium-webdriver/lib/error.js:505:15)
    at parseHttpResponse (/home/jenkins/workspace/syndesis-e2e-tests_master-T3LXHLH4EPAVX4E4OGU73HSCISH2FS2SDVT6KMVDFTLN5LHCVFNA/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/home/jenkins/workspace/syndesis-e2e-tests_master-T3LXHLH4EPAVX4E4OGU73HSCISH2FS2SDVT6KMVDFTLN5LHCVFNA/node_modules/selenium-webdriver/lib/http.js:440:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebElement.click()
    at Driver.schedule (/home/jenkins/workspace/syndesis-e2e-tests_master-T3LXHLH4EPAVX4E4OGU73HSCISH2FS2SDVT6KMVDFTLN5LHCVFNA/node_modules/selenium-webdriver/lib/webdriver.js:816:17)
    at WebElement.schedule_ (/home/jenkins/workspace/syndesis-e2e-tests_master-T3LXHLH4EPAVX4E4OGU73HSCISH2FS2SDVT6KMVDFTLN5LHCVFNA/node_modules/selenium-webdriver/lib/webdriver.js:1921:25)
    at WebElement.click (/home/jenkins/workspace/syndesis-e2e-tests_master-T3LXHLH4EPAVX4E4OGU73HSCISH2FS2SDVT6KMVDFTLN5LHCVFNA/node_modules/selenium-webdriver/lib/webdriver.js:2002:17)
    at actionFn (/home/jenkins/workspace/syndesis-e2e-tests_master-T3LXHLH4EPAVX4E4OGU73HSCISH2FS2SDVT6KMVDFTLN5LHCVFNA/node_modules/@types/protractor/node_modules/protractor/lib/element.ts:94:34)
    at Array.map (native)
    at actionResults.getWebElements.then (/home/jenkins/workspace/syndesis-e2e-tests_master-T3LXHLH4EPAVX4E4OGU73HSCISH2FS2SDVT6KMVDFTLN5LHCVFNA/node_modules/@types/protractor/node_modules/protractor/lib/element.ts:484:67)
    at ManagedPromise.invokeCallback_ (/home/jenkins/workspace/syndesis-e2e-tests_master-T3LXHLH4EPAVX4E4OGU73HSCISH2FS2SDVT6KMVDFTLN5LHCVFNA/node_modules/selenium-webdriver/lib/promise.js:1366:14)
    at TaskQueue.execute_ (/home/jenkins/workspace/syndesis-e2e-tests_master-T3LXHLH4EPAVX4E4OGU73HSCISH2FS2SDVT6KMVDFTLN5LHCVFNA/node_modules/selenium-webdriver/lib/promise.js:2970:14)
    at TaskQueue.executeNext_ (/home/jenkins/workspace/syndesis-e2e-tests_master-T3LXHLH4EPAVX4E4OGU73HSCISH2FS2SDVT6KMVDFTLN5LHCVFNA/node_modules/selenium-webdriver/lib/promise.js:2953:27)
    at asyncRun (/home/jenkins/workspace/syndesis-e2e-tests_master-T3LXHLH4EPAVX4E4OGU73HSCISH2FS2SDVT6KMVDFTLN5LHCVFNA/node_modules/selenium-webdriver/lib/promise.js:2813:27)Error
    at ElementArrayFinder.applyAction_ (/home/jenkins/workspace/syndesis-e2e-tests_master-T3LXHLH4EPAVX4E4OGU73HSCISH2FS2SDVT6KMVDFTLN5LHCVFNA/node_modules/@types/protractor/node_modules/protractor/lib/element.ts:482:23)
    at ElementArrayFinder.(anonymous function).args [as click] (/home/jenkins/workspace/syndesis-e2e-tests_master-T3LXHLH4EPAVX4E4OGU73HSCISH2FS2SDVT6KMVDFTLN5LHCVFNA/node_modules/@types/protractor/node_modules/protractor/lib/element.ts:96:21)
    at ElementFinder.(anonymous function).args [as click] (/home/jenkins/workspace/syndesis-e2e-tests_master-T3LXHLH4EPAVX4E4OGU73HSCISH2FS2SDVT6KMVDFTLN5LHCVFNA/node_modules/@types/protractor/node_modules/protractor/lib/element.ts:873:14)
    at /home/jenkins/workspace/syndesis-e2e-tests_master-T3LXHLH4EPAVX4E4OGU73HSCISH2FS2SDVT6KMVDFTLN5LHCVFNA/e2e/integrations/integration.steps.ts:190:22
    at ManagedPromise.invokeCallback_ (/home/jenkins/workspace/syndesis-e2e-tests_master-T3LXHLH4EPAVX4E4OGU73HSCISH2FS2SDVT6KMVDFTLN5LHCVFNA/node_modules/selenium-webdriver/lib/promise.js:1366:14)
    at TaskQueue.execute_ (/home/jenkins/workspace/syndesis-e2e-tests_master-T3LXHLH4EPAVX4E4OGU73HSCISH2FS2SDVT6KMVDFTLN5LHCVFNA/node_modules/selenium-webdriver/lib/promise.js:2970:14)
    at TaskQueue.executeNext_ (/home/jenkins/workspace/syndesis-e2e-tests_master-T3LXHLH4EPAVX4E4OGU73HSCISH2FS2SDVT6KMVDFTLN5LHCVFNA/node_modules/selenium-webdriver/lib/promise.js:2953:27)
    at asyncRun (/home/jenkins/workspace/syndesis-e2e-tests_master-T3LXHLH4EPAVX4E4OGU73HSCISH2FS2SDVT6KMVDFTLN5LHCVFNA/node_modules/selenium-webdriver/lib/promise.js:2813:27)
    at /home/jenkins/workspace/syndesis-e2e-tests_master-T3LXHLH4EPAVX4E4OGU73HSCISH2FS2SDVT6KMVDFTLN5LHCVFNA/node_modules/selenium-webdriver/lib/promise.js:676:7
    at <anonymous>
```

**Comment by dsimansk** [comment]
Fixed by #44.
