### ISSUE TITLE
fix @integrations-delete test

### ISSUE THREAD

**Issue by jludvice** [syndesisio/syndesis-e2e-tests#72]
![modal](https://user-images.githubusercontent.com/8707241/29763868-3b5456e8-8bd5-11e7-9bfb-fbd279f6e6a4.png)

```
Using syndesis ui on url https://syndesis-qe.b6ff.rh-idev.openshiftapps.com/
[09:40:54] I/launcher - Running 1 instances of WebDriver
[09:40:54] I/direct - Using ChromeDriver directly...
[09:40:55] W/runner - Ignoring unknown extra flags: cucumberOpts. This will be an error in future versions, please use --disableChecks flag to disable the  Protractor CLI flag checks. 
@integrations-delete
Feature: Test to verify delete action

    https://issues.jboss.org/browse/IPAAS-290

cucumber event handlers attached via registerHandler are now passed the associated object instead of an event
getPayloadItem will be removed in the next major release
  @integrations-delete
  Scenario: Create integration as draft and delete it
2017-08-28 09:40:59,342 INFO [root] loading test config from /home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/test_config.json
2017-08-28 09:40:59,356 INFO [root] loaded test config:
 {
    "users": {
        "camilla": {
            "username": "syndesisqe",
            "password": "39fqma53Wyks789b52B@h6GJ",
            "userDetails": {
                "email": "syndesisqe@devnull.com",
                "firstName": "Syndesis",
                "lastName": "QE"
            }
        }
    },
    "connection": {
        "Twitter Listener": {
            "accessToken": "879671681031299072-jJkHttt0VdbXK9W2eTO18UXWc7bnV7n",
            "accessTokenSecret": "IcaN8RF8Qu4kfMX4ujR2AVaSUinEx5sVjOVNtPKD0xDjF",
            "consumerKey": "8ay6yaMzYmoPeLd4tuOv1EIw9",
            "consumerSecret": "f4J148UQwapJdaYUDIpaukwwEZ251mbVrwI4AF6DbWAs03M229"
        },
        "QE Salesforce": {
            "clientId": "3MVG9HxRZv05HarQs27Qlx77A3WZUcfI5XDb8duT86c6hOtqQeLF1b0FX.yZQk355GStt0CLTBO4JqaLcYJm4",
            "clientSecret": "1663828463327160709",
            "password": "ipaas2017",
            "userName": "jbossqa.fuse@gmail.com"
        },
        "Twitter": {
            "accessToken": "randomly generated token",
            "accessTokenSecret": "this is just the biggest secret",
            "consumerKey": "rrrrrrrrrrrrrrrrrrrrrrr333",
            "consumerSecret": "ssssssssssssssssssssssss333"
        }
    }
}
2017-08-28 09:40:59,356 INFO [root] found 1 users in test config
2017-08-28 09:41:01,553 INFO [root] GitHub login page
2017-08-28 09:41:08,815 INFO [root] github login, current url: https://syndesis-qe.b6ff.rh-idev.openshiftapps.com/dashboard
  ✔ When "Camilla" logs into the Syndesis
2017-08-28 09:41:09,769 INFO [root] navigating Camilla to Home page
  ✔ And "Camilla" navigates to the "Home" page
2017-08-28 09:41:11,239 INFO [root] clicking button Create Integration
2017-08-28 09:41:11,239 INFO [root] searching for button Create Integration
2017-08-28 09:41:12,272 INFO [root] searching for button Create Integration
  ✔ And clicks on the "Create Integration" button to create a new integration.
  ✔ Then she is presented with a visual integration editor
  ✔ And she is prompted to select a "Start" connection from a list of available connections
2017-08-28 09:41:12,767 INFO [root] searching for connection Twitter Example
2017-08-28 09:41:12,767 INFO [root] searching for connection Twitter Example
  ✔ When Camilla selects the "Twitter Example" connection
2017-08-28 09:41:12,868 INFO [root] searching for integration action 'Mention'
  ✔ And she selects "Mention" integration action
  ✔ Then she is prompted to select a "Finish" connection from a list of available connections
2017-08-28 09:41:13,288 INFO [root] searching for connection Salesforce Example
2017-08-28 09:41:13,288 INFO [root] searching for connection Salesforce Example
  ✔ When Camilla selects the "Salesforce Example" connection
2017-08-28 09:41:13,381 INFO [root] searching for integration action 'Create Opportunity'
  ✔ And she selects "Create Opportunity" integration action
2017-08-28 09:41:14,035 INFO [root] searching for button Add a Step
  ✔ Then she is presented with the "Add a Step" button
2017-08-28 09:41:14,060 INFO [root] searching for button Save
2017-08-28 09:41:14,086 WARN [root] Save button is not present on integration edit.
2017-08-28 09:41:14,086 INFO [root] searching for button Save as Draft
  ✔ And click on the integration save button
  ✔ And she defines integration name "Awesome integration for delete"
2017-08-28 09:41:14,372 INFO [root] clicking button Save as Draft
2017-08-28 09:41:14,372 INFO [root] searching for button Save as Draft
2017-08-28 09:41:14,425 INFO [root] searching for button Save as Draft
  ✔ And click on the "Save as Draft" button
  ✔ Then Camilla is presented with "Awesome integration for delete" integration details
2017-08-28 09:41:15,820 INFO [root] clicking link Done
2017-08-28 09:41:15,820 INFO [root] searching for link Done
  ✔ And Camilla clicks on the "Done" link
2017-08-28 09:41:15,992 INFO [root] Verifying integration Awesome integration for delete is present
2017-08-28 09:41:15,993 INFO [root] Checking if integration Awesome integration for delete is present in the list
  ✔ And Integration "Awesome integration for delete" is present in integrations list
2017-08-28 09:41:16,271 INFO [root] clicking delete link for integration Awesome integration for delete
[09:41:16] W/element - more than one element found for locator By(css selector, .list-pf-item) - the first result will be used
[09:41:47] E/launcher - Modal not loaded in time
Wait timed out after 30001ms
[09:41:47] E/launcher - TimeoutError: Modal not loaded in time
Wait timed out after 30001ms
    at WebDriverError (/home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/node_modules/selenium-webdriver/lib/error.js:27:5)
    at TimeoutError (/home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/node_modules/selenium-webdriver/lib/error.js:238:5)
    at /home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/node_modules/selenium-webdriver/lib/promise.js:2107:17
    at ManagedPromise.invokeCallback_ (/home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/node_modules/selenium-webdriver/lib/promise.js:1366:14)
    at TaskQueue.execute_ (/home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/node_modules/selenium-webdriver/lib/promise.js:2970:14)
    at TaskQueue.executeNext_ (/home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/node_modules/selenium-webdriver/lib/promise.js:2953:27)
    at asyncRun (/home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/node_modules/selenium-webdriver/lib/promise.js:2813:27)
    at /home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/node_modules/selenium-webdriver/lib/promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: Modal not loaded in time
    at scheduleWait (/home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/node_modules/selenium-webdriver/lib/promise.js:2094:20)
    at ControlFlow.wait (/home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/node_modules/selenium-webdriver/lib/promise.js:2408:12)
    at Driver.wait (/home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/node_modules/selenium-webdriver/lib/webdriver.js:943:29)
    at run (/home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/node_modules/@types/protractor/node_modules/protractor/lib/browser.ts:66:27)
    at ProtractorBrowser.to.(anonymous function) [as wait] (/home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/node_modules/@types/protractor/node_modules/protractor/lib/browser.ts:74:12)
    at IntegrationsListComponent.<anonymous> (/home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/e2e/integrations/list/list.po.ts:51:15)
    at step (/home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/e2e/integrations/list/list.po.ts:32:23)
    at Object.next (/home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/e2e/integrations/list/list.po.ts:13:53)
    at fulfilled (/home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/e2e/integrations/list/list.po.ts:4:58)
    at tryCatch (/home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/node_modules/es6-promise/dist/lib/es6-promise/-internal.js:196:12)
[09:41:47] E/launcher - Process exited with error code 199
error Command failed with exit code 199.
```

**Comment by dsimansk** [comment]
Fixed in #73.
