### ISSUE TITLE
fix delete integration step

### ISSUE THREAD

**Issue by jludvice** [syndesisio/syndesis-e2e-tests#8]
```ts
  clickDeleteIntegration(integrationName: string, rootElement: ElementFinder): P<any> {
    log.info(`clicking delete link for integration ${integrationName}`);
    log.info(`root element ${rootElement}`);

    const parentElement = rootElement.all(by.className('integration')).filter(function(elem, index) {
      return elem.element(by.className('name')).getText().then(function(text) {
        return text === integrationName;
      });
    });

    parentElement.first().element(by.id('dropdownKebabRight9')).click();
    this.rootElement.element(by.linkText('Delete')).click();
    return this.rootElement.element(by.buttonText('Delete')).click();
  }
```

* find better place than `app.po.ts`
* may crash cucumber
```
 ✔ And Integration "One step integration" is present in integrations list
2017-07-10 13:51:29,698 INFO [root] clicking delete link for integration One step integration
2017-07-10 13:51:29,699 INFO [root] root element [object Object]
[13:51:31] E/launcher - Index out of bound. Trying to access element at index: 0, but there are only 0 elements that match locator By(css selector, .integration)
[13:51:31] E/launcher - NoSuchElementError: Index out of bound. Trying to access element at index: 0, but there are only 0 elements that match locator By(css selector, .integration)
    at WebDriverError (/home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/node_modules/selenium-webdriver/lib/error.js:27:5)
    at NoSuchElementError (/home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/node_modules/selenium-webdriver/lib/error.js:168:5)
    at selenium_webdriver_1.promise.all.then (/home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/node_modules/protractor/lib/element.ts:287:17)
    at ManagedPromise.invokeCallback_ (/home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/node_modules/selenium-webdriver/lib/promise.js:1366:14)
    at TaskQueue.execute_ (/home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/node_modules/selenium-webdriver/lib/promise.js:2970:14)
    at TaskQueue.executeNext_ (/home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/node_modules/selenium-webdriver/lib/promise.js:2953:27)
    at asyncRun (/home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/node_modules/selenium-webdriver/lib/promise.js:2813:27)
    at /home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/node_modules/selenium-webdriver/lib/promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:109:7)Error
    at ElementArrayFinder.applyAction_ (/home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/node_modules/protractor/lib/element.ts:482:23)
    at ElementArrayFinder.(anonymous function) [as click] (/home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/node_modules/protractor/lib/element.ts:96:21)
    at ElementFinder.(anonymous function) [as click] (/home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/node_modules/protractor/lib/element.ts:873:14)
    at AppPage.clickDeleteIntegration (/home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/e2e/app.po.ts:155:65)
    at IntegrationSteps.deleteIntegration (/home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/e2e/integrations/integration.steps.ts:61:27)
    at World.bindingFunc (/home/jludvice/devel/redhat/ipaas/syndesis-e2e-tests/node_modules/cucumber-tsflow/src/BindingDecorator.ts:145:85)
[13:51:31] E/launcher - Process exited with error code 199
error Command failed with exit code 199.

```

**Comment by jludvice** [comment]
@lvydra looks like developers changed integration editor -> `Add a Step` button changed  behavior and on click it displays some popup messages...

**Comment by dsimansk** [comment]
@lvydra any progress on this issue?

**Comment by dsimansk** [comment]
I've fixed the main issue via https://github.com/syndesisio/syndesis-e2e-tests/commit/e8fa83fc15113f764ab0f50be4075f1b6156b929. If you guys (@jludvice @lvydra) still feel that it can be further improved pls go ahead. I'm gonna close it for now.

**Comment by lvydra** [comment]
I suspect 
`parentElement.first().element(by.id('dropdownKebabRight9')).click();`
to be a cause of potential falling.
I got some solution for it already.
